### ISSUE TITLE
Algolia API crashes continously.

### ISSUE THREAD

**Issue by ritaknowles** [ameysunu/newsforcovid_swift#2]
Few news articles don't open, giving out **com.apple.WebKit.networking error**

**Comment by ameysunu** [comment]
This usually happens if your iOS device has no internet connection or a bad response from the server. There is no issue with WebKit. I have slightly moderated the code, so the issue would no longer persist from the server side.

**Comment by ritaknowles** [comment]
Alright, I'll have it checked right away. Thanks!
